### ISSUE TITLE
Scroll Monitor inits on import

### ISSUE THREAD

**Issue by stephenbaldwin** [Econify/ad.js#78]
https://github.com/Econify/ad.js/blob/465b0fcdd6c67290b6c3e6fd812bc7b222e302f5/src/utils/scrollMonitor.ts#L114

We shouldn't be initializing any code on import of a module, especially anything that has to do with the window as that will break the ability to import this server side

**Comment by MatthewCMoya** [comment]
Confirmed and Resolved
